package com.ptit.exam.ui.view;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * User: Anhnt
 * Date: 9/4/13
 * Time: 1:51 PM
 */

public class LoginGUI extends JPanel
{
    private JPanel loginCard;
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JButton btnOk;
    private JButton btnCancel;
    private JButton btnRegister;
    private JRadioButton yesRadioButton;
    private JRadioButton noRadioButton;

    public LoginGUI()
    {
        super();
    }

    public void addLoginListenner(ActionListener login)
    {
        btnOk.addActionListener(login);
    }

    public JTextField getTxtUsername()
    {
        return txtUsername;
    }

    public void setTxtUsername(JTextField txtUsername)
    {
        this.txtUsername = txtUsername;
    }

    public JPasswordField getTxtPassword()
    {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword)
    {
        this.txtPassword = txtPassword;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        loginCard = new JPanel();
        loginCard.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:47px:noGrow,top:4dlu:noGrow,center:59px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        final JLabel label1 = new JLabel();
        label1.setText("LOGIN :");
        CellConstraints cc = new CellConstraints();
        loginCard.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("Username : ");
        loginCard.add(label2, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        txtUsername = new JTextField();
        loginCard.add(txtUsername, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        txtPassword = new JPasswordField();
        loginCard.add(txtPassword, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Password : ");
        loginCard.add(label3, cc.xy(1, 5, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:75px:noGrow,left:18dlu:noGrow,fill:max(d;4px):noGrow,left:16dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow"));
        loginCard.add(panel1, cc.xy(3, 11, CellConstraints.DEFAULT, CellConstraints.FILL));
        btnOk = new JButton();
        btnOk.setText("OK");
        panel1.add(btnOk, cc.xy(1, 1));
        btnRegister = new JButton();
        btnRegister.setText("REGISTER");
        panel1.add(btnRegister, cc.xy(3, 1));
        btnCancel = new JButton();
        btnCancel.setText("CANCEL");
        panel1.add(btnCancel, cc.xy(5, 1));
        final JLabel label4 = new JLabel();
        label4.setText("Do you want save username and password ???");
        loginCard.add(label4, cc.xy(3, 7));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        loginCard.add(panel2, cc.xy(3, 9));
        yesRadioButton = new JRadioButton();
        yesRadioButton.setSelected(true);
        yesRadioButton.setText("Yes");
        panel2.add(yesRadioButton, BorderLayout.WEST);
        noRadioButton = new JRadioButton();
        noRadioButton.setText("No");
        panel2.add(noRadioButton, BorderLayout.CENTER);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(yesRadioButton);
        buttonGroup.add(noRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return loginCard;
    }
}
